from enum import Enum
from typing import List, Optional
from pydantic import BaseModel


class ConfluencePage(BaseModel):
    """Represents a Confluence page."""
    id: str
    title: str
    body: str
    space_key: str
    version: int
    url: str


class IssueSeverity(str, Enum):
    """Severity level of a critique."""
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class Critique(BaseModel):
    """A critique generated by the Analyst Agent."""
    issue_type: str
    description: str
    severity: IssueSeverity
    suggestion: Optional[str] = None


class RefinementStatus(str, Enum):
    """Status of the refinement process."""
    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"
    REJECTED = "rejected"


class RefinementResult(BaseModel):
    """The result of a refinement job."""
    page_id: str
    original_content: str
    critiques: List[Critique] = []
    rewritten_content: Optional[str] = None
    status: RefinementStatus
    reviewer_comments: Optional[str] = None


class JobRequest(BaseModel):
    """Request to start a refinement job."""
    page_id: str
    force_refresh: bool = False
