"""Domain records of the curation pipeline."""

from enum import Enum
from typing import List

from pydantic import BaseModel


class CurationStatus(str, Enum):
    APPROVED = "approved"  # automatic checks and reviewer agree
    NEEDS_REVIEW = "needs_review"  # conflicts or doubts: a human must decide
    HUMAN_APPROVED = "human_approved"  # never regenerated by later runs
    FAILED = "failed"


class SourcePage(BaseModel):
    id: str
    title: str
    markdown: str
    path: str = ""
    version: int = 1
    updated_at: str = ""


class Position(BaseModel):
    page_id: str
    statement: str


class Conflict(BaseModel):
    topic: str
    positions: List[Position] = []
    resolution: str = ""
    needs_human: bool = False  # the evidence does not settle which side is right


class Comparison(BaseModel):
    conflicts: List[Conflict] = []
    obsolete_page_ids: List[str] = []


class CuratedDoc(BaseModel):
    id: str
    space_key: str
    title: str
    markdown: str
    status: CurationStatus
    conflicts: List[Conflict] = []
    feedback: str = ""
    source_ids: List[str] = []
